# The Site Configuration

theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Amsterdam

# jekyll-seo-tag settings
title: Tsotne's Blog
tagline: Cybersecurity & Networking
description: >-
  Cybersecurity & Networking

url: "https://tsotne.blog"

github:
  username: cotneok

social:
  name: Tsotne Okrostsvaridze
  email: cotne.ok@gmail.com
  links:
    - https://github.com/cotneok
    - https://www.linkedin.com/in/tsotne-okrostsvaridze-ab1b5958/



# Web Analytics Settings — fill in when ready
analytics:
  google:
    id:
  goatcounter:
    id:

# Sidebar avatar — place your image at assets/img/avatar.jpg in your repo
avatar: /assets/IMG_6074.jpg

theme_mode: dark

toc: true

comments:
  provider: giscus
  giscus:
    repo: cotneok/blog-comments
    repo_id: "R_kgDORuXwzw"
    category: "Announcements"
    category_id: "DIC_kwDORuXwz84C5FQJ"
    mapping: pathname
    strict: 0
    input_position: bottom
    reactions_enabled: 1

cdn:
social_preview_image:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10
baseurl: ""

# ---- Do not modify below unless you know what you're doing ----

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
